import { GetWeeksBySeasonDocument } from '../types/generated-queries';
import { GraphQLError } from 'graphql';

export const getWeeksBySeason = {
  request: {
    query: GetWeeksBySeasonDocument,
    variables: { season: '2021' },
  },
  result: {
    data: {
      weeks: [
        {
          __typename: 'Week',
          id: '22',
          label: 'Week 8',
          games: [],
          gamesCount: 0,
          season: '2021',
          slug: 'week-8',
        },
        {
          __typename: 'Week',
          id: '21',
          label: 'Week 7',
          games: [],
          gamesCount: 0,
          season: '2021',
          slug: 'week-7',
        },
        {
          __typename: 'Week',
          id: '20',
          label: 'Week 6',
          games: [],
          gamesCount: 0,
          season: '2021',
          slug: 'week-6',
        },
        {
          __typename: 'Week',
          id: '19',
          label: 'Week 5',
          games: [],
          gamesCount: 0,
          season: '2021',
          slug: 'week-5',
        },
        {
          __typename: 'Week',
          id: '18',
          label: 'Week 4',
          games: [
            {
              __typename: 'Game',
              id: '22',
              homeTeam: {
                __typename: 'Team',
                id: '2',
                name: 'Falcons',
                city: 'Atlanta',
                abbreviation: 'ATL',
              },
              awayTeam: {
                __typename: 'Team',
                id: '15',
                name: 'Jaguars',
                city: 'Jacksonville',
                abbreviation: 'JAX',
              },
              week: {
                __typename: 'Week',
                id: '18',
              },
              spread: 12,
              winner: null,
              slug: 'falcons-jaguars',
            },
          ],
          gamesCount: 1,
          season: '2021',
          slug: 'week-4',
        },
        {
          __typename: 'Week',
          id: '3',
          label: 'Week 3',
          games: [
            {
              __typename: 'Game',
              id: '23',
              homeTeam: {
                __typename: 'Team',
                id: '21',
                name: 'Vikings',
                city: 'Minnesota',
                abbreviation: 'MIN',
              },
              awayTeam: {
                __typename: 'Team',
                id: '5',
                name: 'Panthers',
                city: 'Carolina',
                abbreviation: 'CAR',
              },
              week: {
                __typename: 'Week',
                id: '3',
              },
              spread: 12,
              winner: null,
              slug: 'vikings-panthers',
            },
            {
              __typename: 'Game',
              id: '19',
              homeTeam: {
                __typename: 'Team',
                id: '22',
                name: 'Patriots',
                city: 'New England',
                abbreviation: 'NE',
              },
              awayTeam: {
                __typename: 'Team',
                id: '29',
                name: 'Seahawks',
                city: 'Seattle',
                abbreviation: 'SEA',
              },
              week: {
                __typename: 'Week',
                id: '3',
              },
              spread: 12,
              winner: null,
              slug: 'patriots-seahawks',
            },
            {
              __typename: 'Game',
              id: '21',
              homeTeam: {
                __typename: 'Team',
                id: '17',
                name: 'Raiders',
                city: 'Las Vegas',
                abbreviation: 'LVR',
              },
              awayTeam: {
                __typename: 'Team',
                id: '28',
                name: '49ers',
                city: 'San Francisco',
                abbreviation: 'SAN',
              },
              week: {
                __typename: 'Week',
                id: '3',
              },
              spread: -10.5,
              winner: null,
              slug: 'raiders-49ers',
            },
            {
              __typename: 'Game',
              id: '24',
              homeTeam: {
                __typename: 'Team',
                id: '20',
                name: 'Dolphins',
                city: 'Miami',
                abbreviation: 'MIA',
              },
              awayTeam: {
                __typename: 'Team',
                id: '9',
                name: 'Cowboys',
                city: 'Dallas',
                abbreviation: 'DAL',
              },
              week: {
                __typename: 'Week',
                id: '3',
              },
              spread: 12,
              winner: null,
              slug: 'dolphins-cowboys',
            },
            {
              __typename: 'Game',
              id: '25',
              homeTeam: {
                __typename: 'Team',
                id: '25',
                name: 'Jets',
                city: 'New York',
                abbreviation: 'NYJ',
              },
              awayTeam: {
                __typename: 'Team',
                id: '30',
                name: 'Buccaneers',
                city: 'Tampa Bay',
                abbreviation: 'TB',
              },
              week: {
                __typename: 'Week',
                id: '3',
              },
              spread: -1,
              winner: null,
              slug: 'jets-buccaneers',
            },
            {
              __typename: 'Game',
              id: '26',
              homeTeam: {
                __typename: 'Team',
                id: '3',
                name: 'Ravens',
                city: 'Baltimore',
                abbreviation: 'BAL',
              },
              awayTeam: {
                __typename: 'Team',
                id: '2',
                name: 'Falcons',
                city: 'Atlanta',
                abbreviation: 'ATL',
              },
              week: {
                __typename: 'Week',
                id: '3',
              },
              spread: 0,
              winner: null,
              slug: 'ravens-falcons',
            },
            {
              __typename: 'Game',
              id: '27',
              homeTeam: {
                __typename: 'Team',
                id: '23',
                name: 'Saints',
                city: 'New Orleans',
                abbreviation: 'NO',
              },
              awayTeam: {
                __typename: 'Team',
                id: '7',
                name: 'Bengals',
                city: 'Cincinnati',
                abbreviation: 'CIN',
              },
              week: {
                __typename: 'Week',
                id: '3',
              },
              spread: -10,
              winner: null,
              slug: 'saints-bengals',
            },
            {
              __typename: 'Game',
              id: '28',
              homeTeam: {
                __typename: 'Team',
                id: '11',
                name: 'Lions',
                city: 'Detroit',
                abbreviation: 'DET',
              },
              awayTeam: {
                __typename: 'Team',
                id: '22',
                name: 'Patriots',
                city: 'New England',
                abbreviation: 'NE',
              },
              week: {
                __typename: 'Week',
                id: '3',
              },
              spread: 16,
              winner: null,
              slug: 'lions-patriots',
            },
          ],
          gamesCount: 8,
          season: '2021',
          slug: 'week-4',
        },
        {
          __typename: 'Week',
          id: '2',
          label: 'Week 2',
          games: [
            {
              __typename: 'Game',
              id: '32',
              homeTeam: {
                __typename: 'Team',
                id: '6',
                name: 'Bears',
                city: 'Chicago',
                abbreviation: 'CHI',
              },
              awayTeam: {
                __typename: 'Team',
                id: '25',
                name: 'Jets',
                city: 'New York',
                abbreviation: 'NYJ',
              },
              week: {
                __typename: 'Week',
                id: '2',
              },
              spread: 8,
              winner: null,
              slug: 'bears-jets',
            },
            {
              __typename: 'Game',
              id: '17',
              homeTeam: {
                __typename: 'Team',
                id: '10',
                name: 'Broncos',
                city: 'Denver',
                abbreviation: 'DEN',
              },
              awayTeam: {
                __typename: 'Team',
                id: '31',
                name: 'Titans',
                city: 'Tennessee',
                abbreviation: 'TEN',
              },
              week: {
                __typename: 'Week',
                id: '2',
              },
              spread: 5,
              winner: null,
              slug: 'broncos-titans',
            },
            {
              __typename: 'Game',
              id: '41',
              homeTeam: {
                __typename: 'Team',
                id: '9',
                name: 'Cowboys',
                city: 'Dallas',
                abbreviation: 'DAL',
              },
              awayTeam: {
                __typename: 'Team',
                id: '12',
                name: 'Packers',
                city: 'Green Bay',
                abbreviation: 'GB',
              },
              week: {
                __typename: 'Week',
                id: '2',
              },
              spread: -10,
              winner: null,
              slug: 'cowboys-packers',
            },
            {
              __typename: 'Game',
              id: '42',
              homeTeam: {
                __typename: 'Team',
                id: '6',
                name: 'Bears',
                city: 'Chicago',
                abbreviation: 'CHI',
              },
              awayTeam: {
                __typename: 'Team',
                id: '2',
                name: 'Falcons',
                city: 'Atlanta',
                abbreviation: 'ATL',
              },
              week: {
                __typename: 'Week',
                id: '2',
              },
              spread: 2,
              winner: null,
              slug: 'bears-falcons',
            },
          ],
          gamesCount: 4,
          season: '2021',
          slug: 'week-2',
        },
        {
          __typename: 'Week',
          id: '1',
          label: 'Week 1',
          games: [
            {
              __typename: 'Game',
              id: '30',
              homeTeam: {
                __typename: 'Team',
                id: '29',
                name: 'Seahawks',
                city: 'Seattle',
                abbreviation: 'SEA',
              },
              awayTeam: {
                __typename: 'Team',
                id: '32',
                name: 'Football Team',
                city: 'Washington',
                abbreviation: 'WAS',
              },
              week: {
                __typename: 'Week',
                id: '1',
              },
              spread: -1.5,
              winner: null,
              slug: 'seahawks-football-team',
            },
            {
              __typename: 'Game',
              id: '14',
              homeTeam: {
                __typename: 'Team',
                id: '17',
                name: 'Raiders',
                city: 'Las Vegas',
                abbreviation: 'LVR',
              },
              awayTeam: {
                __typename: 'Team',
                id: '28',
                name: '49ers',
                city: 'San Francisco',
                abbreviation: 'SAN',
              },
              week: {
                __typename: 'Week',
                id: '1',
              },
              spread: 2,
              winner: null,
              slug: 'raiders-49ers',
            },
            {
              __typename: 'Game',
              id: '13',
              homeTeam: {
                __typename: 'Team',
                id: '13',
                name: 'Texans',
                city: 'Houston',
                abbreviation: 'HOU',
              },
              awayTeam: {
                __typename: 'Team',
                id: '19',
                name: 'Rams',
                city: 'Los Angeles',
                abbreviation: 'LAR',
              },
              week: {
                __typename: 'Week',
                id: '1',
              },
              spread: -14,
              winner: null,
              slug: 'texans-rams',
            },
            {
              __typename: 'Game',
              id: '12',
              homeTeam: {
                __typename: 'Team',
                id: '6',
                name: 'Bears',
                city: 'Chicago',
                abbreviation: 'CHI',
              },
              awayTeam: {
                __typename: 'Team',
                id: '7',
                name: 'Bengals',
                city: 'Cincinnati',
                abbreviation: 'CIN',
              },
              week: {
                __typename: 'Week',
                id: '1',
              },
              spread: 10,
              winner: null,
              slug: 'bears-bengals',
            },
            {
              __typename: 'Game',
              id: '11',
              homeTeam: {
                __typename: 'Team',
                id: '1',
                name: 'Cardinals',
                city: 'Arizona',
                abbreviation: 'ARI',
              },
              awayTeam: {
                __typename: 'Team',
                id: '18',
                name: 'Chargers',
                city: 'Los Angeles',
                abbreviation: 'LAC',
              },
              week: {
                __typename: 'Week',
                id: '1',
              },
              spread: -1,
              winner: null,
              slug: 'cardinals-chargers',
            },
            {
              __typename: 'Game',
              id: '6',
              homeTeam: {
                __typename: 'Team',
                id: '22',
                name: 'Patriots',
                city: 'New England',
                abbreviation: 'NE',
              },
              awayTeam: {
                __typename: 'Team',
                id: '23',
                name: 'Saints',
                city: 'New Orleans',
                abbreviation: 'NO',
              },
              week: {
                __typename: 'Week',
                id: '1',
              },
              spread: 7,
              winner: {
                __typename: 'Team',
                id: '22',
              },
              slug: 'patriots-saints',
            },
          ],
          gamesCount: 6,
          season: '2021',
          slug: 'week-1',
        },
      ],
    },
  },
};

export const getWeeksBySeasonNoWeeks = {
  request: {
    query: GetWeeksBySeasonDocument,
    variables: { season: '2021' },
  },
  result: {
    data: {
      weeks: [],
    },
  },
};

export const getWeeksBySeasonNetworkError = {
  request: {
    query: GetWeeksBySeasonDocument,
    variables: { season: '2021' },
  },
  error: new Error('[Network error]: An error occurred'),
};

export const getWeeksBySeasonGraphqlError = {
  request: {
    query: GetWeeksBySeasonDocument,
    variables: { season: '2021' },
  },
  result: {
    errors: [new GraphQLError('[GraphQL error]: Error!')],
  },
};
