export const selectedWeek = {
  __typename: 'Week',
  id: 'ckvi58ic10183kq0hf8w966r8',
  label: 'Week 1',
  slug: 'week-1',
  season: '2021',
  gamesCount: 15,
  games: [
    {
      __typename: 'Game',
      id: 'ckvikw4v10475l50hjgrlqyb0',
      slug: 'cardinals-falcons',
      homeTeam: {
        __typename: 'Team',
        id: 'ckvi5a5290000ps0hudlff6x8',
        name: 'Cardinals',
        city: 'Arizona',
        abbreviation: 'ARI',
      },
      awayTeam: {
        __typename: 'Team',
        id: 'ckvi5a52m0007ps0h5vxqp06k',
        name: 'Falcons',
        city: 'Atlanta',
        abbreviation: 'ATL',
      },
      week: {
        __typename: 'Week',
        id: 'ckvi58ic10183kq0hf8w966r8',
      },
      spread: 1,
      winner: null,
    },
    {
      __typename: 'Game',
      id: 'ckvil0skx1855l50hj2d3347q',
      slug: 'lions-packers',
      homeTeam: {
        __typename: 'Team',
        id: 'ckvi5a5380070ps0hatdsgid6',
        name: 'Lions',
        city: 'Detroit',
        abbreviation: 'DET',
      },
      awayTeam: {
        __typename: 'Team',
        id: 'ckvi5a53a0077ps0hn4j95l46',
        name: 'Packers',
        city: 'Green Bay',
        abbreviation: 'GB',
      },
      week: {
        __typename: 'Week',
        id: 'ckvi58ic10183kq0hf8w966r8',
      },
      spread: 13,
      winner: null,
    },
    {
      __typename: 'Game',
      id: 'ckvk3x2ub7342k30heiop7cgi',
      slug: 'jets-texans',
      homeTeam: {
        __typename: 'Team',
        id: 'ckvi5a5440168ps0hxc3fhwrr',
        name: 'Jets',
        city: 'New York',
        abbreviation: 'NYJ',
      },
      awayTeam: {
        __typename: 'Team',
        id: 'ckvi5a53c0084ps0hdouko31b',
        name: 'Texans',
        city: 'Houston',
        abbreviation: 'HOU',
      },
      week: {
        __typename: 'Week',
        id: 'ckvi58ic10183kq0hf8w966r8',
      },
      spread: 9,
      winner: null,
    },
    {
      __typename: 'Game',
      id: 'ckvk3yjcs8477k30hk7b8yb9t',
      slug: 'titans-raiders',
      homeTeam: {
        __typename: 'Team',
        id: 'ckvi5a54s0210ps0hrdwu7p9m',
        name: 'Titans',
        city: 'Tennessee',
        abbreviation: 'TEN',
      },
      awayTeam: {
        __typename: 'Team',
        id: 'ckvi5a53q0112ps0hs0sf0vzf',
        name: 'Raiders',
        city: 'Las Vegas',
        abbreviation: 'OAK',
      },
      week: {
        __typename: 'Week',
        id: 'ckvi58ic10183kq0hf8w966r8',
      },
      spread: 1,
      winner: null,
    },
    {
      __typename: 'Game',
      id: 'ckvk45eel8762k30ht6ji71rx',
      slug: 'chiefs-jaquars',
      homeTeam: {
        __typename: 'Team',
        id: 'ckvi5a53o0105ps0hwc1qh7kj',
        name: 'Chiefs',
        city: 'Kansas City',
        abbreviation: 'KC',
      },
      awayTeam: {
        __typename: 'Team',
        id: 'ckvi5a53j0098ps0hjhs8qwhn',
        name: 'Jaquars',
        city: 'Jacksonville',
        abbreviation: 'JAX',
      },
      week: {
        __typename: 'Week',
        id: 'ckvi58ic10183kq0hf8w966r8',
      },
      spread: 13,
      winner: null,
    },
    {
      __typename: 'Game',
      id: 'ckvk47nkg9071k30hydp8bgr8',
      slug: 'vikings-chargers',
      homeTeam: {
        __typename: 'Team',
        id: 'ckvi5a53w0140ps0hhgi59qso',
        name: 'Vikings',
        city: 'Minnesota',
        abbreviation: 'MIN',
      },
      awayTeam: {
        __typename: 'Team',
        id: 'ckvi5a53r0119ps0hnrh745js',
        name: 'Chargers',
        city: 'Los Angeles',
        abbreviation: 'SD',
      },
      week: {
        __typename: 'Week',
        id: 'ckvi58ic10183kq0hf8w966r8',
      },
      spread: 12,
      winner: null,
    },
    {
      __typename: 'Game',
      id: 'ckvk5qck816438k30h18b6g8p5',
      slug: 'dolphins-patriots',
      homeTeam: {
        __typename: 'Team',
        id: 'ckvi5a53v0133ps0hhnuaui15',
        name: 'Dolphins',
        city: 'Miami',
        abbreviation: 'MIA',
      },
      awayTeam: {
        __typename: 'Team',
        id: 'ckvi5a53y0147ps0hvl6o3m94',
        name: 'Patriots',
        city: 'New England',
        abbreviation: 'NE',
      },
      week: {
        __typename: 'Week',
        id: 'ckvi58ic10183kq0hf8w966r8',
      },
      spread: 12,
      winner: null,
    },
    {
      __typename: 'Game',
      id: 'ckvikwb870634l50h239qhozr',
      slug: 'ravens-bills',
      homeTeam: {
        __typename: 'Team',
        id: 'ckvi5a52p0014ps0h2qvk8yu2',
        name: 'Ravens',
        city: 'Baltimore',
        abbreviation: 'BAL',
      },
      awayTeam: {
        __typename: 'Team',
        id: 'ckvi5a52r0021ps0h76uyk7um',
        name: 'Bills',
        city: 'Buffalo',
        abbreviation: 'BUF',
      },
      week: {
        __typename: 'Week',
        id: 'ckvi58ic10183kq0hf8w966r8',
      },
      spread: 2,
      winner: {
        __typename: 'Team',
        id: 'ckvi5a52r0021ps0h76uyk7um',
      },
    },
    {
      __typename: 'Game',
      id: 'ckvmbuh3d4065q80h50m5607q',
      slug: 'football-team-ravens',
      homeTeam: {
        __typename: 'Team',
        id: 'ckvi5a54u0217ps0h42b7qjnd',
        name: 'Football Team',
        city: 'Washington',
        abbreviation: 'WAS',
      },
      awayTeam: {
        __typename: 'Team',
        id: 'ckvi5a52p0014ps0h2qvk8yu2',
        name: 'Ravens',
        city: 'Baltimore',
        abbreviation: 'BAL',
      },
      week: {
        __typename: 'Week',
        id: 'ckvi58ic10183kq0hf8w966r8',
      },
      spread: 12,
      winner: null,
    },
    {
      __typename: 'Game',
      id: 'ckvikwy1b1096l50hs6cmin2m',
      slug: 'bengals-browns',
      homeTeam: {
        __typename: 'Team',
        id: 'ckvi5a52z0042ps0h48oj5zo7',
        name: 'Bengals',
        city: 'Cincinnati',
        abbreviation: 'CIN',
      },
      awayTeam: {
        __typename: 'Team',
        id: 'ckvi5a5310049ps0ht2kbff3h',
        name: 'Browns',
        city: 'Cleveland',
        abbreviation: 'CLE',
      },
      week: {
        __typename: 'Week',
        id: 'ckvi58ic10183kq0hf8w966r8',
      },
      spread: 13,
      winner: null,
    },
    {
      __typename: 'Game',
      id: 'ckvk5ri5y16771k30hkhgxy4z4',
      slug: 'broncos-patriots',
      homeTeam: {
        __typename: 'Team',
        id: 'ckvi5a5350063ps0hg7dul255',
        name: 'Broncos',
        city: 'Denver',
        abbreviation: 'DEN',
      },
      awayTeam: {
        __typename: 'Team',
        id: 'ckvi5a53y0147ps0hvl6o3m94',
        name: 'Patriots',
        city: 'New England',
        abbreviation: 'NE',
      },
      week: {
        __typename: 'Week',
        id: 'ckvi58ic10183kq0hf8w966r8',
      },
      spread: 3,
      winner: null,
    },
    {
      __typename: 'Game',
      id: 'ckvk6i3zk24342k30hyxui0jd4',
      slug: 'broncos-raiders',
      homeTeam: {
        __typename: 'Team',
        id: 'ckvi5a5350063ps0hg7dul255',
        name: 'Broncos',
        city: 'Denver',
        abbreviation: 'DEN',
      },
      awayTeam: {
        __typename: 'Team',
        id: 'ckvi5a53q0112ps0hs0sf0vzf',
        name: 'Raiders',
        city: 'Las Vegas',
        abbreviation: 'OAK',
      },
      week: {
        __typename: 'Week',
        id: 'ckvi58ic10183kq0hf8w966r8',
      },
      spread: 12,
      winner: null,
    },
    {
      __typename: 'Game',
      id: 'ckvmbv2af4829q80htxqb9yfw',
      slug: '49ers-packers',
      homeTeam: {
        __typename: 'Team',
        id: 'ckvi5a54a0189ps0hzdyz0hhq',
        name: '49ers',
        city: 'San Francisco',
        abbreviation: 'SF',
      },
      awayTeam: {
        __typename: 'Team',
        id: 'ckvi5a53a0077ps0hn4j95l46',
        name: 'Packers',
        city: 'Green Bay',
        abbreviation: 'GB',
      },
      week: {
        __typename: 'Week',
        id: 'ckvi58ic10183kq0hf8w966r8',
      },
      spread: 4,
      winner: null,
    },
    {
      __typename: 'Game',
      id: 'ckvi5b43u0109qw0havmkhu2t',
      slug: 'bills-panthers',
      homeTeam: {
        __typename: 'Team',
        id: 'ckvi5a52r0021ps0h76uyk7um',
        name: 'Bills',
        city: 'Buffalo',
        abbreviation: 'BUF',
      },
      awayTeam: {
        __typename: 'Team',
        id: 'ckvi5a52u0028ps0he4jd7hsg',
        name: 'Panthers',
        city: 'Carolina',
        abbreviation: 'CAR',
      },
      week: {
        __typename: 'Week',
        id: 'ckvi58ic10183kq0hf8w966r8',
      },
      spread: -10,
      winner: null,
    },
    {
      __typename: 'Game',
      id: 'ckvil0jbj1504l50hl59l4m7h',
      slug: 'cowboys-broncos',
      homeTeam: {
        __typename: 'Team',
        id: 'ckvi5a5330056ps0hfszu3bez',
        name: 'Cowboys',
        city: 'Dallas',
        abbreviation: 'DAL',
      },
      awayTeam: {
        __typename: 'Team',
        id: 'ckvi5a5350063ps0hg7dul255',
        name: 'Broncos',
        city: 'Denver',
        abbreviation: 'DEN',
      },
      week: {
        __typename: 'Week',
        id: 'ckvi58ic10183kq0hf8w966r8',
      },
      spread: -5,
      winner: {
        __typename: 'Team',
        id: 'ckvi5a5330056ps0hfszu3bez',
      },
    },
  ],
};
